[options]
db_host = db
db_port = 5432
db_user = odoo
; db_password wird vom Docker-Entrypoint via PASSWORD env-Variable gesetzt

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

admin_passwd = PickingPoc2024!
dbfilter = ^(picking|masterfischer)$
list_db = True
proxy_mode = True

workers = 2
max_cron_threads = 1
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 600
limit_time_real = 1200

log_level = info
log_handler = :INFO
